import { DLC_QUESTS, DLC_QUEST_ACCESS, DLC_REGIONS, DLC_TRANSITION_RISKS } from './content/dlc-quests.js';
export const FLAG_LABELS = {
  limgrave: 'Reached Limgrave', roundtable: 'Reached Roundtable Hold', ranniStory: 'Ranni story milestone',
  frenziedFlame: 'Received the Frenzied Flame', forgeReached: 'Reached the Forge of the Giants', frenziedNullified: 'Nullified the Frenzied Flame', erdtreeFire: 'Erdtree state changed',
  godrickRune: "Godrick's Great Rune", radahnRune: "Radahn's Great Rune", morgottRune: "Morgott's Great Rune",
  rykardRune: "Rykard's Great Rune", mohgRune: "Mohg's Great Rune", maleniaRune: "Malenia's Great Rune", unbornRune: 'Great Rune of the Unborn',
  margit: 'Margit defeated', godrick: 'Godrick defeated', rennala: 'Rennala defeated', radahn: 'Radahn defeated',
  rykard: 'Rykard defeated', morgott: 'Morgott defeated', fireGiant: 'Fire Giant defeated', mohg: 'Mohg defeated',
  malenia: 'Malenia defeated', maliketh: 'Maliketh defeated', fireGiantDefeated: 'Fire Giant defeated', malikethDefeated: 'Maliketh defeated', eldenBeast: 'Elden Beast defeated',
  torrent: 'Torrent unlocked', craftingKit: 'Crafting Kit obtained', physick: 'Flask of Wondrous Physick obtained',
  spiritBell: 'Spirit Calling Bell obtained', whetstone: 'Whetstone Knife obtained', tailoring: 'Tailoring Tools obtained',
  firstStepGrace: 'The First Step grace', stormhillGrace: 'Stormhill Shack grace', waypointGrace: 'Waypoint Ruins grace', secludedCellGrace: 'Secluded Cell grace',
  morneRampartGrace: 'Castle Morne Rampart grace', morneMoangraveGrace: 'Morne Moangrave grace', liurniaGrace: 'Lake-Facing Cliffs grace',
  liurniaShoreGrace: 'Liurnia Lake Shore grace', dectusGrace: 'Grand Lift of Dectus grace', fourBelfriesGrace: 'The Four Belfries grace', ranniRiseGrace: "Ranni's Rise grace",
  stormveilGateGrace: 'Stormveil Main Gate grace', godrickGrace: 'Godrick grace', margitGrace: 'Margit grace',
  capitalGrace: 'Elden Throne grace', erdtreeSanctuaryGrace: 'Erdtree Sanctuary grace', eastCapitalGrace: 'East Capital Rampart grace', ainselMainGrace: 'Ainsel River Main grace', siofraGrace: 'Siofra River Bank grace', nightsSacredGroundGrace: "Night's Sacred Ground grace",
  malikethGrace: 'Maliketh grace', greatBridgeGrace: 'Beside the Great Bridge grace', volcanoManorGrace: 'Volcano Manor grace', audiencePathwayGrace: 'Audience Pathway grace', frenziedProscriptionGrace: 'Frenzied Flame Proscription grace',
  altusGrace: 'Altus Plateau grace', gelmirGrace: 'First Mt. Gelmir Campsite grace', caelidGrace: 'Smoldering Church grace', mountaintopsGrace: 'Zamor Ruins grace',
  redmanePlazaGrace: 'Redmane Castle Plaza grace', chamberPlazaGrace: 'Chamber Outside the Plaza grace', radahnGrace: 'Starscourge Radahn grace', footForgeGrace: 'Foot of the Forge grace', fireGiantGrace: 'Fire Giant grace',
  ageFracture: 'Age of Fracture ending', ageStars: 'Age of Stars ending', frenziedEnding: 'Lord of Frenzied Flame ending',
  perfectOrderRune: 'Mending Rune of Perfect Order', deathPrinceRune: 'Mending Rune of the Death-Prince', fellCurseRune: 'Mending Rune of the Fell Curse',
  dlcEntry:'Entered the Realm of Shadow', dlcBelurat:'Reached Belurat', dlcEnsis:'Reached Castle Ensis', dlcScaduAltus:'Reached Scadu Altus',
  dlcShadowKeep:'Reached Shadow Keep', dlcStorehouse:'Reached the Specimen Storehouse', dlcMessmerDoor:'Reached Messmer’s final approach', dlcRauh:'Reached Ancient Ruins of Rauh',
  dlcAbyss:'Reached Abyssal Woods', dlcJaggedPeak:'Reached Jagged Peak', dlcCerulean:'Reached Cerulean Coast', dlcFissure:'Reached Stone Coffin Fissure', dlcBayleDoor:'Reached Jagged Peak Summit', dlcEnirIlim:'Reached Enir-Ilim',
  dancingLionDefeated:'Divine Beast Dancing Lion defeated', rellanaDefeated:'Rellana defeated', messmerDefeated:'Messmer defeated', rominaDefeated:'Romina defeated', bayleDefeated:'Bayle defeated',
  putrescentDefeated:'Putrescent Knight defeated', metyrDefeated:'Metyr defeated', midraDefeated:'Midra defeated', gaiusDefeated:'Commander Gaius defeated', scadutreeAvatarDefeated:'Scadutree Avatar defeated', consortDefeated:'DLC final boss defeated',
};

export const BRANCHES = [
  { id:'wander', title:'Keep exploring', icon:'✦', text:'A quick safety check, then I stay out of the way.' },
  { id:'nudge', title:'Give me a nudge', icon:'◌', text:'One small direction based on what the save says you have done.' },
  { id:'missed', title:'Did I miss anything?', icon:'◇', text:'A short essentials check with no giant completion wall.' },
  { id:'main', title:'Where is the main path?', icon:'↑', text:'Start vague and reveal more only if you ask.' },
  { id:'npc', title:'Who should I check on?', icon:'♙', text:'Surface one NPC thread that makes sense at your current stage.' },
  { id:'session', title:'What should we do tonight?', icon:'☾', text:'Three options for a co-op session, with the new player’s pace first.' },
];

export const STAGES = [
  { id:'tutorial', when:f=>!f.limgrave, title:'The very beginning', area:'Chapel / tutorial', summary:'Take your time learning movement and combat. Nothing important is on a timer here.', hints:['Follow the path that looks deliberately constructed.','The tutorial is optional, but useful for a first Souls game.','Continue until the world opens into Limgrave.'] },
  { id:'limgrave-start', when:f=>f.limgrave&&!f.torrent, title:'First steps in Limgrave', area:'Limgrave', summary:'Wander, touch graces, and get comfortable before worrying about bosses.', hints:['Following the road north is useful, but detours are encouraged.','Rest at a few Sites of Grace along the main road.','The game will introduce a faster way to travel after enough early exploration.'] },
  { id:'limgrave', when:f=>f.torrent&&!f.margit, title:'Explore Limgrave freely', area:'Limgrave & Weeping Peninsula', summary:'This is a great time to explore. The castle can wait until the group feels ready.', hints:['The southern landmass is a good first large detour.','If the castle entrance feels punishing, explore elsewhere and return.','The clearest main path follows grace toward the large castle.'] },
  { id:'stormveil', when:f=>f.margit&&!f.godrick, title:'Inside the first legacy dungeon', area:'Stormveil Castle', summary:'Stormveil rewards curiosity. Side rooms and vertical paths matter more than moving quickly.', hints:['Explore doors, rooftops and side rooms before following a faster teammate.','Several NPC threads begin or advance inside the castle.','Your major objective is deeper inside Stormveil.'] },
  { id:'liurnia', when:f=>f.godrick&&!f.rennala, title:'The world just got much wider', area:'Liurnia of the Lakes', summary:'Liurnia is intentionally broad. Pick a landmark and wander; there is no need to clear it in one direction.', hints:['The enormous structure in the lake is the clearest main objective.','Northwestern Liurnia contains one of the game’s largest optional stories.','Look for a way into the academy in the lake when you want main progression.'] },
  { id:'branches', when:f=>f.rennala&&!f.radahn, title:'Several good directions', area:'Liurnia / Caelid / Altus approaches', summary:'There is no single correct next region. This is a good stretch for NPC stories and side exploration.', hints:['Caelid is much more relevant now, but still dangerous.','A major Liurnia thread can point toward an important Caelid event.','You can pursue another Great Rune or work toward the plateau north of Liurnia.'] },
  { id:'midgame', when:f=>f.radahn&&!f.morgott, title:'Follow what changed', area:'Altus & the underground', summary:'A major event changed what is possible. Revisit NPCs before pushing hard toward the capital.', hints:['Something dramatic changed in Limgrave after the festival.','Both underground routes and the plateau are meaningful directions.','Main-story momentum eventually leads toward the huge capital beneath the Erdtree.'] },
  { id:'mountaintops', when:f=>f.morgott&&!f.fireGiant, title:'A new road opens', area:'Mountaintops of the Giants', summary:'You are entering a later-game stretch. The site will warn you before the largest world-state changes.', hints:['The newly opened route from the capital is the intended direction.','Explore the mountaintops before rushing the giant landmark.','The main objective is the enormous forge visible in the region.'] },
  { id:'late', when:f=>f.fireGiant&&!f.eldenBeast, title:'Late game', area:'Beyond the Mountaintops', summary:'Major world-state changes are active or close. Check unfinished NPC threads before obvious one-way prompts.', hints:['This is the point to finish NPC business you care about.','Optional regions remain, but the world can change significantly.','Continue the story interaction at the forge when the group is ready.'] },
  { id:'cleanup', when:()=>true, title:'Endgame / cleanup', area:'The Lands Between', summary:'Use the NPC tracker, map and missed-content check for anything you still want to see.', hints:['Revisit unfinished NPC threads.','Look for optional regions you never fully explored.','Choose remaining goals instead of following a fixed route.'] },
];

export const BASE_REGIONS = [
  { id:'limgrave', name:'Limgrave', x:45, y:72, clue:'The opening fields and roads.', when:f=>f.limgrave||f.firstStepGrace },
  { id:'weeping', name:'Weeping Peninsula', x:39, y:87, clue:'The southern peninsula.', when:f=>f.morneRampartGrace||f.morneMoangraveGrace },
  { id:'stormveil', name:'Stormveil Castle', x:35, y:62, clue:'The castle overlooking Limgrave.', when:f=>f.margit||f.stormveilGateGrace||f.godrick },
  { id:'liurnia', name:'Liurnia', x:28, y:49, clue:'The broad lake region north of Stormveil.', when:f=>f.liurniaGrace||f.godrick },
  { id:'caelid', name:'Caelid', x:61, y:73, clue:'The scarlet land to the east.', when:f=>f.caelidGrace||f.radahn },
  { id:'altus', name:'Altus Plateau', x:42, y:35, clue:'The golden plateau farther north.', when:f=>f.altusGrace||f.radahn||f.morgott },
  { id:'gelmir', name:'Mt. Gelmir', x:24, y:34, clue:'The volcanic western highlands.', when:f=>f.gelmirGrace||f.rykard },
  { id:'leyndell', name:'Leyndell', x:50, y:39, clue:'The royal capital beneath the Erdtree.', when:f=>f.eastCapitalGrace||f.capitalGrace||f.morgott },
  { id:'mountaintops', name:'Mountaintops', x:62, y:20, clue:'The snowy northern heights.', when:f=>f.mountaintopsGrace||f.morgott||f.fireGiant },
  { id:'underground', name:'Underground', x:52, y:59, clue:'Hidden rivers and eternal cities.', when:f=>f.siofraGrace||f.radahn||f.ranniStory, hiddenOnMap:true },
];

export const REGIONS = [...BASE_REGIONS, ...DLC_REGIONS];

export const MAP_IMAGE = {
  url:'https://i.imgur.com/af4DRnx.jpeg',
  source:'https://imgur.com/gallery/elden-ring-world-map-no-icons-8k-jpg-af4DRnx',
  label:'Icon-free Lands Between map',
  credit:'In-game map art © FromSoftware / Bandai Namco; prototype reference image hosted on Imgur.'
};

const IMAGES = {
  ranni:{src:'https://cdn.mos.cms.futurecdn.net/v2/t%3A0%2Cl%3A420%2Ccw%3A1080%2Cch%3A1080%2Cq%3A80%2Cw%3A1080/T3UL9aPcv7wQt9hT7PtqXh.jpg',credit:'FromSoftware image via GamesRadar / Future',source:'https://www.gamesradar.com/games/action-rpg/ive-somehow-been-living-a-chilling-lie-for-over-200-hours-of-elden-ring-but-at-least-im-not-the-only-one/'},
  roderika:{src:'https://img.consolepulse.com/uploads/franchises/elden-ring/characters/Roderika.webp',credit:'FromSoftware image via Console Pulse',source:'https://consolepulse.com/multiplatform/elden-ring/guides/elden-ring-character-guide'},
  sellen:{src:'https://multiplayer.net-cdn.it/thumbs/images/2024/05/31/sellen_cella_jpg_800x0_crop_upscale_q85.jpg',credit:'FromSoftware image via Multiplayer.it',source:'https://multiplayer.it/soluzioni/elden-ring-sellen-come-completare-la-missione-della-strega.html'},
  alexander:{src:'https://images.gamewatcherstatic.com/image/file/0/be/117480/Elden-Ring-Characters-1.jpg',credit:'FromSoftware image via GameWatcher',source:'https://www.gamewatcher.com/news/elden-ring-characters'},
  blaidd:{src:'https://cdn.mos.cms.futurecdn.net/v2/t%3A0%2Cl%3A420%2Ccw%3A1080%2Cch%3A1080%2Cq%3A80%2Cw%3A1080/Lwanz47yzqqXbXZKuzRA27.jpg',credit:'FromSoftware image via PC Gamer / Future',source:'https://www.pcgamer.com/elden-ring-blaidd-quest-armor-darriwil/'},
  nepheli:{src:'https://cdn.mos.cms.futurecdn.net/v2/t%3A0%2Cl%3A420%2Ccw%3A1080%2Cch%3A1080%2Cq%3A80%2Cw%3A1080/tZPE3fzmiJ98FzpPH4h3vn.jpg',credit:'FromSoftware image via PC Gamer / Future',source:'https://www.pcgamer.com/elden-ring-nepheli-location-seluvis-potion-choice/'},
  fia:{src:'https://staticdelivery.nexusmods.com/images/4333/51148826-1662497870.png',credit:'Screenshot by iSapphic via Nexus Mods',source:'https://www.nexusmods.com/eldenring/images/1405'},
  latenna:{src:'https://www.gamerguides.com/assets/media/15/83918/latenna_elden_ring-1c8bc305.png',credit:'FromSoftware image via Gamer Guides',source:'https://www.gamerguides.com/elden-ring-shadow-of-the-erdtree/database/npcs/npcs/latenna-the-albinauric'},
};

const step = (label, area, clue, detail=label) => ({ label, area, clue, detail });

export const BASE_QUESTS = [
  {id:'varre',name:'White Mask Varré',area:'Limgrave → Liurnia',regions:['limgrave','liurnia'],priority:'side',hint:'His path starts almost immediately, but it is safe to leave alone for a long while.',steps:[step('Met the masked man near the beginning','Limgrave','Check the first grace after emerging into the open world.'),step('Checked back after earning a Great Rune','Limgrave / Roundtable','A major early victory changes what he has to say.'),step('Found his later meeting place','Liurnia','A ruined church in the lake region matters to him.'),step('Completed his initiation','Liurnia / Altus','He asks you to prove something before giving a blood-soaked task.'),step('Followed his invitation to its destination','Late optional area','His final reward points to a dangerous hidden region.')],saveEvidence:[['godrickRune','A Great Rune is present, so his post-Great-Rune dialogue should be available.'],['mohg','The boss tied to the end of this thread is already defeated.']]},
  {id:'boc',name:'Boc the Seamster',area:'Limgrave → Leyndell',regions:['limgrave','liurnia','altus'],priority:'side',hint:'Listen carefully for a voice near a road in Limgrave.',steps:[step('Found someone calling for help','Limgrave','Listen rather than looking for a person standing in the open.'),step('Helped recover something important to him','Coastal Limgrave','A small coastal dungeon is connected to him.'),step('Met him again after leaving Limgrave','Liurnia','He relocates near Sites of Grace as you travel.'),step('Reached a decision about his future','Altus / Leyndell','A late conversation can have very different outcomes; avoid rushing the obvious option.')],saveEvidence:[['tailoring','The Tailoring Tools are in the save, which strongly overlaps this thread.']]},
  {id:'roderika',name:'Roderika',area:'Stormhill → Roundtable Hold',regions:['limgrave','stormveil'],priority:'major',hint:'A lonely shack on the road toward the castle is worth stopping at.',image:IMAGES.roderika,steps:[step('Met her on the road','Stormhill','Stop at the shack on the road to the castle.'),step('Investigated her concern in Stormveil','Stormveil','A disturbing room inside the castle holds something meaningful to her.'),step('Checked on her after she moved','Roundtable Hold','She relocates to the hub as the early story advances.'),step('Helped her find a purpose','Roundtable Hold','Talk between her and the blacksmith until both understand what she can do.')],saveEvidence:[['stormhillGrace','The grace beside her first location is active.'],['spiritBell','Your save has the Spirit Calling Bell.'],['roundtable','Roundtable Hold has been reached.']]},
  {id:'alexander',name:'Iron Fist Alexander',area:'Limgrave → Farum Azula',regions:['limgrave','caelid','altus'],priority:'major',hint:'If you hear someone shouting for help near a road, investigate.',image:IMAGES.alexander,steps:[step('Helped him out of a predicament','Limgrave','Listen for a loud voice near northern Limgrave.'),step('Found him around the festival','Caelid','A major festival becomes the next natural meeting point.'),step('Spoke with him after the festival','Caelid','Do not immediately leave after the big fight.'),step('Crossed paths again while traveling north','Liurnia / Mt. Gelmir','He appears in more than one optional location.'),step('Reached the final meeting','Very late game','His story concludes in a late mandatory area.')],saveEvidence:[['radahn','The festival boss is defeated; check the battlefield before forgetting this thread.'],['fireGiant','Late-game progression means his final meeting may be available soon.']]},
  {id:'blaidd',name:'Blaidd',area:'Mistwood → Ranni’s path',regions:['limgrave','liurnia','underground'],priority:'major',hint:'The Mistwood has an unusual sound cue. A merchant may know what it means.',image:IMAGES.blaidd,steps:[step('Heard about a strange figure in the woods','Mistwood','Pay attention to howling around the ruins.'),step('Made contact','Mistwood','A nearby merchant can teach you how to respond.'),step('Helped with his target','South Limgrave','His target is connected to an evergaol.'),step('Reconnected through a larger questline','Liurnia / underground','His story becomes woven into another character’s very long quest.')],saveEvidence:[['ranniRiseGrace',"Ranni's Rise grace is active, so Blaidd's larger story can be in motion."],['radahn','The festival milestone that intersects his story is complete.'],['ranniStory','The save has a major Ranni-story flag.']]},
  {id:'iji',name:'War Counselor Iji',area:'Liurnia → Ranni’s path',regions:['liurnia','underground'],priority:'major',hint:'A giant smith on the road to Caria Manor knows much more about Blaidd and Ranni than he first says.',steps:[step('Met Iji','Road to the Manor','Follow the western Liurnia road toward Caria Manor and stop at the giant smith.'),step('Returned after joining Ranni','Road to the Manor','His dialogue changes once you enter Ranni’s service.'),step('Checked on him as Blaidd’s situation changed','Liurnia','Revisit Iji after major steps in Ranni and Blaidd’s story; he gives important context rather than a separate fetch quest.'),step('Returned after Ranni’s path reached its late stage','Road to the Manor','One final visit reveals the cost of what happened to Ranni’s inner circle.')],saveEvidence:[['ranniRiseGrace',"Ranni's Rise is reached, so Iji’s Ranni-related dialogue can be active."],['radahn','Radahn is defeated, advancing the fate shared by Ranni, Blaidd, and Iji.'],['ainselMainGrace','Ranni’s path is in its later phase; Iji has important follow-up dialogue.']]},
  {id:'irina',name:'Irina & Edgar',area:'Weeping Peninsula',regions:['weeping'],priority:'major',hint:'The road into the Weeping Peninsula introduces this story naturally.',steps:[step('Met Irina','Weeping Peninsula','Follow the main road just after crossing south.'),step('Carried her request toward the castle','Castle Morne','Her request points directly to the fortress at the peninsula’s tip.'),step('Found Edgar','Castle Morne','Explore the castle rather than heading straight to its boss.'),step('Returned after the castle was resolved','Weeping Peninsula','Check back after dealing with the castle’s major threat.')],saveEvidence:[['morneRampartGrace','The save shows you reached Castle Morne’s approach.'],['morneMoangraveGrace','The grace after Castle Morne’s boss area is active.']]},
  {id:'kenneth',name:'Kenneth Haight',area:'Limgrave',regions:['limgrave'],priority:'side',hint:'Listen for a very loud noble calling from above a road.',steps:[step('Met Kenneth','East Limgrave','Listen along the road east of the lake.'),step('Helped reclaim his fort','Fort Haight','His request is tied to the fort in southeastern Limgrave.'),step('Returned to him afterward','Limgrave','Go back to the place where you first met him.'),step('Checked on him again later','Stormveil','His story eventually intersects another Limgrave succession thread.')],saveEvidence:[['morgott','Late capital progression can unlock the conclusion of the Limgrave succession threads.']]},
  {id:'nepheli',name:'Nepheli Loux',area:'Stormveil → Liurnia',regions:['stormveil','liurnia'],priority:'major',hint:'Explore side rooms shortly before Stormveil’s main boss.',image:IMAGES.nepheli,steps:[step('Met Nepheli','Stormveil','Look through side rooms near the final stretch of the castle.'),step('Spoke again after Stormveil','Roundtable Hold','Check the hub after the castle boss.'),step('Found her during a difficult moment','Liurnia','A village beneath the southwestern plateau matters to her.'),step('Helped her choose a future','Roundtable / Stormveil','A unique item from the starting area and another Limgrave NPC can influence the resolution.')],saveEvidence:[['godrick','Godrick is defeated, so her Roundtable phase should be available if you met her.'],['morgott','The late trigger for her best outcome is now satisfied.']]},
  {id:'rogier',name:'Sorcerer Rogier',area:'Stormveil → Roundtable',regions:['stormveil','liurnia'],priority:'side',hint:'Stormveil has a chapel that is easy to walk past.',steps:[step('Met Rogier in Stormveil','Stormveil','Search for a chapel inside the castle.'),step('Spoke at the Roundtable','Roundtable Hold','He relocates after the castle.'),step('Investigated what interested him','Stormveil depths','There is a hidden route far below the castle.'),step('Followed the thread into a larger mystery','Liurnia','His research points toward a much larger questline.')],saveEvidence:[['roundtable','Roundtable Hold is available.'],['ranniStory','The larger mystery this quest feeds into has progressed.']]},
  {id:'ranni',name:'Ranni the Witch',area:'Liurnia → underground',regions:['liurnia','underground'],priority:'major',hint:'Northwestern Liurnia hides a large estate with an important thread beyond it.',image:IMAGES.ranni,steps:[step('Met her properly in Liurnia','Northwest Liurnia','Explore beyond the large manor in the northwest.'),step('Agreed to help','Three Sisters','Speak with everyone she introduces before leaving.'),step('Worked with her allies','Siofra / Caelid','Her allies point you toward an underground mystery and a festival.'),step('Followed what changed after the festival','Limgrave / Nokron','A major battle changes the landscape in a visible way.'),step('Carried the journey through the underground','Nokstella / Lake of Rot','Her path keeps going long after the first underground city.'),step('Reached the final place tied to her story','Moonlight Altar','The conclusion is beyond an area that looks inaccessible from lower Liurnia.')],saveEvidence:[['ranniRiseGrace',"Ranni's Rise grace is active."],['ranniStory','A major Ranni story flag is active.'],['ageStars','The Age of Stars ending has been completed.']]},
  {id:'seluvis',name:'Preceptor Seluvis',area:'Three Sisters → Altus',regions:['liurnia','altus'],priority:'side',hint:'Once you begin Ranni’s service, one of her associates has a separate and very time-sensitive agenda.',steps:[step('Met Seluvis through Ranni','Three Sisters','Speak with everyone Ranni introduces before leaving her tower.'),step('Resolved his first request','Liurnia / Roundtable','His request intersects another NPC’s future, so choose carefully.'),step('Found what he was hiding','Three Sisters','The ruins near the towers conceal more than they appear to.'),step('Followed his private scheme','Altus Plateau','A rare amber item on the plateau advances his optional reward path.'),step('Finished what you wanted before Ranni moved on','Three Sisters','Do this before handing Ranni the important treasure from Nokron.')],saveEvidence:[['ranniRiseGrace',"Ranni's Rise is active, so Seluvis can be encountered."],['nightsSacredGroundGrace',"Night's Sacred Ground is reached; the Nokron hand-in that ends Seluvis's quest is now close."]]},
  {id:'sellen',name:'Sorceress Sellen',area:'Limgrave → Raya Lucaria',regions:['limgrave','liurnia'],priority:'major',hint:'Search the ruins east of the starting area carefully; there is more below them.',image:IMAGES.sellen,steps:[step('Found Sellen','Limgrave','Look below ruins east of the starting area.'),step('Learned more after reaching the academy region','Liurnia / Mt. Gelmir','A legendary sorcerer in the volcanic region can move her story.'),step('Found someone she asked about','Caelid','Her request eventually points to a hidden cave in dangerous territory.'),step('Reached the final choice','Raya Lucaria','Her conclusion appears near the academy after enough of the story is complete.')],saveEvidence:[['waypointGrace','Waypoint Ruins grace is active, right beside her first location.'],['rennala','The academy’s main boss is defeated, allowing the later phases of her quest.']]},
  {id:'fia',name:'Fia',area:'Roundtable → Deeproot',regions:['underground'],priority:'major',hint:'Her early interactions seem optional, but her story becomes much larger later.',image:IMAGES.fia,steps:[step('Met Fia','Roundtable Hold','She is present in the hub from early on.'),step('Learned she had a deeper purpose','Roundtable Hold','Keep checking the hub after major Great Rune progress.'),step('Followed clues connected to death','Liurnia / underground','Her story overlaps Rogier and a mark tied to a divine tower.'),step('Found her much later underground','Deeproot Depths','A deep hidden region eventually becomes her destination.'),step('Resolved her story','Deeproot Depths','Her final outcome can produce a unique mending rune.')],saveEvidence:[['roundtable','Roundtable Hold has been reached.'],['deathPrinceRune','The Mending Rune of the Death-Prince confirms this quest outcome.']]},
  {id:'millicent',name:'Millicent & Gowry',area:'Caelid → Haligtree',regions:['caelid','altus','mountaintops'],priority:'major',hint:'Southern Caelid contains a shack and nearby town tied to this story.',steps:[step('Found Gowry’s shack','Caelid','Search south of Sellia.'),step('Helped the woman he mentioned','Caelid','The cure requires a needle connected to a nearby commander.'),step('Met her again after Caelid','Altus approaches','Her journey resumes after she leaves Caelid.'),step('Followed her north','Altus / Mountaintops','She appears at several grace-adjacent stops.'),step('Reached her final decision','Haligtree','Her conclusion is in one of the game’s most hidden late regions.')],saveEvidence:[['malenia','The boss at the end of the region tied to her story is defeated.'],['frenziedNullified','The save shows the Frenzied Flame was nullified, which requires the late reward from this quest path.']]},
  {id:'hyetta',name:'Hyetta',area:'Liurnia → Leyndell depths',regions:['liurnia','leyndell'],priority:'major',hint:'She can appear shortly after entering Liurnia if another southern story has concluded.',steps:[step('Met Hyetta','Liurnia','Look near the first grace after Stormveil.'),step('Helped her several times','Liurnia','Her repeated request uses the same unusual item.'),step('Followed her journey north','Liurnia','She relocates along a rough northward path.'),step('Discovered where her path leads','Leyndell depths','Her conclusion is beneath the capital, behind a very hidden route.')],saveEvidence:[['liurniaGrace','The first Liurnia grace is active, where her path can begin.'],['frenziedFlame','The save shows the Frenzied Flame was received.'],['frenziedEnding','The Lord of Frenzied Flame ending is complete.']]},
  {id:'diallos',name:'Diallos & Jar-Bairn',area:'Roundtable → Jarburg',regions:['liurnia','altus'],priority:'side',hint:'This quest crosses several regions, so do not worry if it goes quiet for a long time.',steps:[step('Met Diallos','Roundtable Hold','He starts in the hub.'),step('Found the person he was seeking','Liurnia','Look around the academy-gate-town area.'),step('Checked on him at a manor','Mt. Gelmir','His path can intersect the manor faction.'),step('Visited the village of jars','Liurnia','A small settlement is hidden below eastern cliffs.'),step('Returned after events changed','Jarburg','Revisit more than once after other progress.')],saveEvidence:[['roundtable','Roundtable Hold is active.'],['liurniaGrace','Liurnia has been reached.']]},
  {id:'corhyn',name:'Brother Corhyn & Goldmask',area:'Roundtable → Altus',regions:['altus','leyndell'],priority:'major',hint:'After the capital route opens, this thread becomes much more active.',steps:[step('Met Corhyn','Roundtable Hold','He begins in the hub.'),step('Found him after he left','Altus Plateau','He moves once enough Great Rune progress is made.'),step('Helped him reconnect with his teacher','Altus Plateau','His teacher is hard to miss visually once you know to look for a silent figure.'),step('Solved their later puzzle','Leyndell','A very specific incantation/stat puzzle is required for the full ending path.')],saveEvidence:[['roundtable','Roundtable Hold has been reached.'],['perfectOrderRune','The Mending Rune of Perfect Order confirms this quest outcome.']]},
  {id:'latenna',name:'Latenna',area:'Liurnia → Consecrated Snowfield',regions:['liurnia','mountaintops'],priority:'major',hint:'Southwestern Liurnia has a cave leading somewhere unexpectedly important.',image:IMAGES.latenna,steps:[step('Found the hidden village lead','Liurnia','Search beneath the southwest plateau.'),step('Met Latenna','Liurnia','A cave leads to a secluded shack beyond it.'),step('Accepted her request','Liurnia','She asks to travel with you if you possess the right medallion half.'),step('Carried it into a very late region','Consecrated Snowfield','Her destination is far north and easy to overlook.')],saveEvidence:[['liurniaGrace','Liurnia has been reached.'],['morgott','The route toward her late destination can now open.']]},
  {id:'volcano',name:'Volcano Manor household',area:'Mt. Gelmir',regions:['gelmir'],priority:'major',hint:'Treat the manor like a hub: talk to everyone again whenever one assignment changes.',steps:[step('Received an invitation or found the manor','Liurnia / Mt. Gelmir','There are multiple routes to the manor.'),step('Joined the household','Volcano Manor','Accepting lets you access several intertwined NPC stories.'),step('Completed available requests before the manor boss','Various','Finish the letters and re-check residents before killing the area’s lord if you want the most dialogue/rewards.'),step('Checked every resident between requests','Volcano Manor','Several residents move or reveal new steps after each contract.')],saveEvidence:[['rykardRune',"Rykard's Great Rune is present; manor contracts may no longer all be available."],['rykard','Rykard is defeated.']]},
  {id:'yura',name:'Bloody Finger Hunter Yura',area:'Limgrave → Altus',regions:['limgrave','liurnia','altus'],priority:'side',hint:'A hunter under a ruin near the lake warns you about a nearby dragon.',steps:[step('Met Yura','Limgrave','Check beneath ruined stonework near the lake.'),step('Helped with an invasion','Limgrave','An invasion along the river can pull him into your world.'),step('Found his next sign','Liurnia','Look near the academy’s main gate without using the seal.'),step('Reached his later encounter','Altus Plateau','A church on the plateau matters to his story.')],saveEvidence:[['liurniaGrace','Liurnia has been reached.'],['morgott','Late progression can replace Yura with another story state.']]},
  {id:'thops',name:'Thops',area:'Liurnia / Raya Lucaria',regions:['liurnia'],priority:'side',hint:'A quiet church just after entering Liurnia contains a small academy-related story.',steps:[step('Met Thops','Liurnia','Stop at the church near the southern lake entrance.'),step('Found a spare academy key','Raya Lucaria','One key opens the academy; another can be found inside.'),step('Returned with the spare','Liurnia','He can finally return to the academy.'),step('Found where his research led','Raya Lucaria','Check the academy again after he leaves.')],saveEvidence:[['liurniaGrace','Liurnia has been reached.'],['rennala','Raya Lucaria is fully open for exploration.']]},
  {id:'gurranq',name:'Gurranq / D, Hunter of the Dead',area:'Limgrave → Dragonbarrow',regions:['limgrave','caelid'],priority:'side',hint:'A hunter of Those Who Live in Death can introduce you to a much stranger figure.',steps:[step('Met D or found a Deathroot','Limgrave','A village in northeastern Limgrave is an early lead.'),step('Used the unusual waygate','Limgrave → Dragonbarrow','D can mark a shortcut on the map.'),step('Fed Deathroot over time','Bestial Sanctum','Return as you find more Deathroot; rewards come in stages.'),step('Handled the dangerous midpoint','Bestial Sanctum','At one threshold he reacts violently; damage him enough to calm him, not kill him.')],saveEvidence:[['roundtable','D can appear in Roundtable Hold.']]},
  {id:'dung',name:'Dung Eater',area:'Roundtable → Leyndell',regions:['leyndell'],priority:'major',hint:'A disturbing red phantom eventually appears in the hub; his quest is intentionally grim.',steps:[step('Met the red phantom','Roundtable Hold','He appears after enough capital progression.'),step('Found a Seedbed Curse','Leyndell','One of his key items unlocks more dialogue.'),step('Found his physical location','Subterranean Shunning-Grounds','His cell is beneath the capital.'),step('Resolved his ending path or stopped it','Leyndell / underground','His full route requires several Seedbed Curses and can produce a mending rune.')],saveEvidence:[['morgott','The capital is far enough along for this quest to be active.'],['fellCurseRune','The Mending Rune of the Fell Curse confirms the quest ending path.']]},
  {id:'patches',name:'Patches',area:'Limgrave → Mt. Gelmir',regions:['limgrave','liurnia','gelmir'],priority:'side',hint:'A familiar troublemaker is hiding in an early Limgrave cave.',steps:[step('Found Patches','Limgrave','Explore the cave along the river north of the lake.'),step('Spared him and checked his shop','Limgrave','Do not keep attacking after he clearly gives up if you want the quest.'),step('Found his next schemes','Liurnia / Mt. Gelmir','He relocates more than once as you head north.'),step('Checked in during Volcano Manor','Mt. Gelmir','His request there is easy to miss among the other contracts.')],saveEvidence:[['rykard','If Rykard is already defeated, revisit manor residents and old locations for aftermath states.']]},
  {id:'rya',name:'Rya / Zorayas',area:'Liurnia → Volcano Manor',regions:['liurnia','gelmir'],priority:'major',hint:'A polite woman in southern Liurnia has lost something important.',steps:[step('Met Rya','Liurnia','Look around the southern lake area.'),step('Recovered what was taken from her','Liurnia','A nearby merchant has the item.'),step('Accepted her invitation','Liurnia / Altus','She can help you reach the manor once you reach the plateau.'),step('Investigated the manor’s secret','Volcano Manor','Hidden walls and the manor’s underside matter to her identity.'),step('Made a final choice about her future','Volcano Manor','Her final request has several possible resolutions; do not answer reflexively.')],saveEvidence:[['liurniaGrace','Liurnia is reached.'],['rykard','Rykard is defeated; her final manor state may have changed.']]},
  {id:'bernahl',name:'Knight Bernahl',area:'Limgrave → Volcano Manor',regions:['limgrave','gelmir'],priority:'side',hint:'A knight at a shack sells combat skills long before his larger story becomes clear.',steps:[step('Met Bernahl','Limgrave','Visit the shack east of Stormhill.'),step('Met him again at the manor','Volcano Manor','He joins the same household as several other quest NPCs.'),step('Completed his request before the manor lord','Leyndell','His contract should be done before ending the manor’s main quest.'),step('Found his final encounter','Very late game','His last appearance happens in a mandatory late area.')],saveEvidence:[['rykard','Rykard is defeated, which closes some manor dialogue.'],['fireGiant','Late-game progression means Bernahl’s final encounter is approaching.']]},
];

export const QUESTS = [...BASE_QUESTS, ...DLC_QUESTS];

export const getQuest = id => QUESTS.find(q=>q.id===id);
export const getStage = flags => STAGES.find(s=>s.when(flags)) ?? STAGES.at(-1);

export const QUEST_ACCESS = {
  varre:f=>f.limgrave,
  boc:f=>f.limgrave,
  roderika:f=>f.stormhillGrace||f.roundtable,
  alexander:f=>f.limgrave,
  blaidd:f=>f.limgrave,
  iji:f=>f.liurniaGrace||f.ranniRiseGrace,
  irina:f=>f.morneRampartGrace||f.morneMoangraveGrace||f.pilgrimageGrace,
  kenneth:f=>f.limgrave,
  nepheli:f=>f.margit||f.secludedCellGrace||f.stormveilGateGrace,
  rogier:f=>f.margit||f.secludedCellGrace||f.stormveilGateGrace,
  ranni:f=>f.liurniaGrace||f.ranniRiseGrace,
  seluvis:f=>f.ranniRiseGrace,
  sellen:f=>f.waypointGrace||f.liurniaGrace,
  fia:f=>f.roundtable,
  millicent:f=>f.caelidGrace||f.radahn,
  hyetta:f=>f.liurniaGrace||f.frenziedProscriptionGrace,
  diallos:f=>f.roundtable||f.liurniaGrace,
  corhyn:f=>f.roundtable,
  latenna:f=>f.liurniaGrace,
  volcano:f=>f.gelmirGrace||f.volcanoManorGrace||f.audiencePathwayGrace,
  yura:f=>f.limgrave,
  thops:f=>f.liurniaGrace,
  gurranq:f=>f.limgrave||f.roundtable||f.caelidGrace,
  dung:f=>f.eastCapitalGrace||f.capitalGrace||f.morgott,
  patches:f=>f.limgrave,
  rya:f=>f.liurniaGrace||f.volcanoManorGrace,
  bernahl:f=>f.stormhillGrace||f.gelmirGrace||f.volcanoManorGrace,
};

export const questAvailable = (quest, flags) => Boolean((DLC_QUEST_ACCESS[quest.id] ?? QUEST_ACCESS[quest.id])?.(flags) ?? quest.regions.some(id=>REGIONS.find(r=>r.id===id)?.when(flags)));

export const BASE_TRANSITION_RISKS = [
  {
    id:'stormveil-main-boss',level:'note',questIds:['nepheli','rogier','roderika'],triggerFlags:['secludedCellGrace','godrick'],outcomeFlag:'godrick',
    when:f=>f.secludedCellGrace&&!f.godrick,
    title:'Before the main Stormveil boss',
    text:'I’d check on Nepheli and Rogier before starting the castle’s main boss if you want their Stormveil-specific interactions. Roderika also has one castle-related thread worth resolving.',
    aftermath:f=>f.godrick?'Stormveil’s main boss is down. Some castle-specific NPC interactions may have been skipped, but their larger stories can still continue.':'You reached the final Stormveil approach. This is a good point to check Nepheli, Rogier, and Roderika before starting the main boss.',
  },
  {
    id:'altus-festival',level:'note',questIds:['blaidd','alexander'],triggerFlags:['altusGrace'],outcomeFlag:'altusGrace',
    when:f=>!f.altusGrace&&!f.radahn&&(f.dectusGrace||f.rennala),
    title:'Before moving onto Altus',
    text:'I’d check on Blaidd and Alexander before resting in Altus if you want their earlier setup. Reaching Altus can start the Radahn Festival and move some of their dialogue forward.',
    aftermath:'You reached Altus. The Radahn Festival may now be active, which can advance Blaidd and Alexander past earlier interactions.',
  },
  {
    id:'radahn-festival',level:'note',questIds:['blaidd','alexander'],triggerFlags:['chamberPlazaGrace','radahn'],outcomeFlag:'radahn',
    when:f=>(f.redmanePlazaGrace||f.chamberPlazaGrace)&&!f.radahn,
    title:'Before starting the festival boss',
    text:'I’d talk to Blaidd and Alexander around Redmane Castle before starting the boss. After the fight, check the battlefield for both of them before moving on.',
    aftermath:f=>f.radahn?'The festival boss is down. Blaidd and Alexander both have immediate post-fight interactions on the battlefield that are easy to walk away from.':'You reached the boss-side festival grace. Talk to Blaidd and Alexander before starting the fight, then check the battlefield for them afterward.',
  },
  {
    id:'seluvis-nokron',level:'warn',questIds:['seluvis'],triggerFlags:['nightsSacredGroundGrace','ainselMainGrace'],
    when:f=>f.nightsSacredGroundGrace&&!f.ainselMainGrace,
    title:'Before handing over Nokron’s treasure',
    text:'If you care about Seluvis’s optional story or reward, finish it before giving Ranni the important item from Nokron. That hand-in ends Seluvis’s quest.',
    aftermath:f=>f.ainselMainGrace?'Ranni’s underground route has moved forward. If you already handed her the Nokron treasure, Seluvis’s optional story may already be closed.':'Night’s Sacred Ground is reached. Seluvis is now time-sensitive because Ranni’s next major hand-in can end his quest.',
  },
  {
    id:'rykard-lockout',level:'danger',questIds:['volcano','rya','bernahl','patches'],triggerFlags:['audiencePathwayGrace','rykard'],outcomeFlag:'rykard',
    when:f=>f.audiencePathwayGrace&&!f.rykard,
    title:'Before fighting the lord of Volcano Manor',
    text:'I’d finish the Manor contracts and check Rya, Bernahl, Patches, and Tanith before this boss. Defeating Rykard closes remaining Volcano Manor quest steps and moves the household into aftermath states.',
    aftermath:f=>f.rykard?'Rykard is defeated. Remaining Volcano Manor contracts and some resident interactions may now be unavailable.':'You reached the approach to Volcano Manor’s lord. This is the safest point to finish contracts and check every resident before starting the boss.',
  },
  {
    id:'forge-threshold',level:'danger',questIds:['corhyn','nepheli','fia','gurranq'],triggerFlags:['footForgeGrace','fireGiant','erdtreeFire'],outcomeFlag:'erdtreeFire',always:true,
    when:f=>f.footForgeGrace&&!f.erdtreeFire,
    title:'Pause at the Forge',
    text:f=>f.fireGiant?'The Fire Giant is down. I would check Corhyn/Goldmask, Nepheli, Fia/D, and any Roundtable business you care about before using the Forge. The next interaction is the real world-state threshold.':'You are at the Foot of the Forge. The boss itself is not the biggest cutoff; after winning, do not rush the next Forge interaction before checking NPC business.',
    aftermath:f=>f.erdtreeFire?'The Forge event happened. Several NPCs relocate or advance, and the game moves into a much later world state.':f.fireGiant?'The Fire Giant is down. The next Forge interaction is the actual world-state threshold, so pause here for NPC cleanup.':'You reached the Foot of the Forge. The upcoming boss is not the final cutoff; the interaction after it is the bigger story threshold.',
  },
  {
    id:'maliketh-capital',level:'danger',questIds:['corhyn','dung','boc'],triggerFlags:['greatBridgeGrace','maliketh'],outcomeFlag:'maliketh',always:true,
    when:f=>f.greatBridgeGrace&&!f.maliketh,
    title:'Before the boss beyond the Great Bridge',
    text:'I’d finish anything you still want in normal Leyndell and check Corhyn/Goldmask, Dung Eater, and Boc before this boss. Victory changes the capital into its late-game state and removes some locations/interactions.',
    aftermath:f=>f.maliketh?'Maliketh is defeated. Leyndell has changed into its late-game state, so some earlier capital locations and NPC interactions are no longer available.':'You reached the final bridge approach in Farum Azula. This is the last safe checkpoint before the capital changes state.',
  },
  {
    id:'frenzied-door',level:'danger',questIds:['hyetta','millicent'],triggerFlags:['frenziedProscriptionGrace','frenziedFlame'],outcomeFlag:'frenziedFlame',always:true,
    when:f=>f.frenziedProscriptionGrace&&!f.frenziedFlame,
    title:'Before opening the sealed door here',
    text:'This is a major ending-state choice. Opening the unusual door commits you to the Frenzied Flame path and changes Melina’s relationship with you. A reversal exists, but it requires a long optional route tied to Millicent.',
    aftermath:f=>f.frenziedFlame?'The Frenzied Flame was inherited. Other endings are blocked unless the separate reversal path is completed, and Melina’s state changes permanently.':'You reached the Frenzied Flame Proscription. The sealed door here is a major ending-state decision, not ordinary exploration.',
  },
];

export const TRANSITION_RISKS = [...BASE_TRANSITION_RISKS, ...DLC_TRANSITION_RISKS];

export const getTransitionRisk = id => TRANSITION_RISKS.find(r=>r.id===id);
