import assert from 'node:assert/strict';
import { DLC_QUESTS, DLC_REGIONS, DLC_TRANSITION_RISKS } from '../content/dlc-quests.js';
import { STORY_BEATS, GLOSSARY, THEORY_CARDS, STORY_VIDEOS, unlockedStory } from '../content/story-data.js';
import { AREA_RECOMMENDATIONS, BOSS_RECOMMENDATIONS, recommendationForMap } from '../content/recommendations.js';
import { QUEST_ITEM_LINKS } from '../content/item-links.js';
import { ENDING_PATHS, endingPriority, endingWarning, mendingPathsVisible, pathStatus } from '../content/mending-paths.js';
import { BOSS_INSIGHTS } from '../content/boss-insights.js';
import { ACTIVITY_CATEGORIES, COMPLETION_CATALOG_SOURCE } from '../content/completion-catalog.js';

assert.ok(DLC_QUESTS.length >= 12,'Expected the main Shadow of the Erdtree NPC threads.');
assert.ok(DLC_REGIONS.length >= 10,'Expected broad Realm of Shadow map coverage.');
assert.ok(DLC_TRANSITION_RISKS.some(r=>r.id==='dlc-charm-break'));
assert.ok(DLC_TRANSITION_RISKS.some(r=>r.id==='dlc-sealing-tree'&&r.level==='danger'));
assert.ok(STORY_BEATS.some(b=>b.id==='dlc-charm'));
assert.ok(STORY_BEATS.some(b=>b.id==='dlc-end'));
assert.ok(GLOSSARY.some(g=>g.id==='miquella')&&GLOSSARY.some(g=>g.id==='metyr'));
assert.ok(THEORY_CARDS.every(card=>typeof card.unlock==='function'));
assert.ok(STORY_VIDEOS.every(video=>/^https:\/\//.test(video.url)));
assert.equal(STORY_VIDEOS.find(video=>video.id==='base-lore').unlock({eldenBeast:false}),false,'Full base lore video must stay hidden before base-game completion.');
assert.ok(unlockedStory({limgrave:true}).every(beat=>beat.when({limgrave:true})));
assert.equal(recommendationForMap('Shadow Keep, Specimen Storehouse')?.id,'shadow-keep');
assert.ok(BOSS_RECOMMENDATIONS.some(b=>b.name==='Messmer the Impaler'));
assert.ok(AREA_RECOMMENDATIONS.some(a=>a.id==='enir'));
assert.ok(QUEST_ITEM_LINKS.some(item=>item.key==='secretRiteScroll'&&item.questIds.includes('ansbach')));
assert.equal(ENDING_PATHS.length,7);
assert.equal(mendingPathsVisible({godrickRune:true,unbornRune:true}),true);
assert.equal(pathStatus(ENDING_PATHS.find(p=>p.id==='order'),{perfectOrderRune:true}).state,'ready');
assert.equal(pathStatus(ENDING_PATHS.find(p=>p.id==='order'),{},()=> 'unseen').state,'hidden');
assert.equal(pathStatus(ENDING_PATHS.find(p=>p.id==='stars'),{},id=>id==='ranni'?'started':'unseen').state,'progress');
assert.equal(endingPriority('ranni','stars'),2);
assert.equal(endingWarning('stars',{frenziedFlame:true,frenziedNullified:false}).level,'danger');
assert.ok(BOSS_INSIGHTS['Godrick the Grafted']);
assert.ok(ACTIVITY_CATEGORIES.some(([id])=>id==='evergaol'));
assert.equal(COMPLETION_CATALOG_SOURCE.license,'MIT');
console.log(`PASS: ${DLC_QUESTS.length} DLC NPC threads, ${DLC_TRANSITION_RISKS.length} DLC transition warnings, story/glossary, level guidance, videos, and quest-item links are internally coherent.`);
