// Permanent Roundtable upgrade-material unlocks. Exact locations stay behind an
// explicit reveal so this system can surface "an upgrade source is reachable"
// without turning natural exploration into a shopping checklist.
export const FORGE_SUPPLY = [
  { id:'smithing-1', family:'regular', name:"Smithing-Stone Miner's Bell Bearing [1]", region:'liurnia', regionName:'Liurnia of the Lakes', location:'Raya Lucaria Crystal Tunnel', source:'Defeat the Crystalian at the end of the tunnel.', unlocks:['Smithing Stone [1]','Smithing Stone [2]','Glintstone Scrap'], clue:'A mining tunnel in Liurnia contains the first permanent source for early regular weapon stones.', when:f=>Boolean(f.liurniaGrace) },
  { id:'smithing-2', family:'regular', name:"Smithing-Stone Miner's Bell Bearing [2]", region:'altus', regionName:'Altus Plateau', location:'Sealed Tunnel', source:'Open the chest behind the first illusory wall.', unlocks:['Smithing Stone [3]','Smithing Stone [4]','Explosive Stone'], clue:'A sealed mining passage near the capital hides the next regular-stone supply unlock.', when:f=>Boolean(f.altusGrace||f.capitalGrace) },
  { id:'smithing-3', family:'regular', name:"Smithing-Stone Miner's Bell Bearing [3]", region:'mountaintops', regionName:'Mountaintops of the Giants', location:'Zamor Ruins', source:'Found in a chest in the underground portion of the ruins.', unlocks:['Smithing Stone [5]','Smithing Stone [6]'], clue:'A ruined settlement in the Mountaintops contains a permanent mid-late regular-stone supply unlock.', when:f=>Boolean(f.mountaintopsGrace) },
  { id:'smithing-4', family:'regular', name:"Smithing-Stone Miner's Bell Bearing [4]", region:'mountaintops', regionName:'Crumbling Farum Azula', location:'Dragon Temple', source:'Defeat the Godskin Duo.', unlocks:['Smithing Stone [7]','Smithing Stone [8]'], clue:'Late story progression eventually makes the final regular-stone shop upgrade unavoidable.', when:f=>Boolean(f.erdtreeFire||f.greatBridgeGrace) },
  { id:'somber-1', family:'somber', name:"Somberstone Miner's Bell Bearing [1]", region:'caelid', regionName:'Caelid', location:'Sellia Crystal Tunnel', source:'Defeat the Fallingstar Beast at the end of the tunnel.', unlocks:['Somber Smithing Stone [1]','Somber Smithing Stone [2]','Glintstone Scrap'], clue:'A dangerous crystal tunnel in Caelid contains the first permanent source for early somber stones.', when:f=>Boolean(f.caelidGrace) },
  { id:'somber-2', family:'somber', name:"Somberstone Miner's Bell Bearing [2]", region:'altus', regionName:'Altus Plateau', location:'Altus Tunnel', source:'Defeat the Crystalian duo.', unlocks:['Somber Smithing Stone [3]','Somber Smithing Stone [4]','Cracked Crystal'], clue:'One of Altus’s mining tunnels contains the next permanent somber-stone supply unlock.', when:f=>Boolean(f.altusGrace) },
  { id:'somber-3', family:'somber', name:"Somberstone Miner's Bell Bearing [3]", region:'mountaintops', regionName:'Mountaintops of the Giants', location:'First Church of Marika', source:'Found on a corpse outside the church.', unlocks:['Somber Smithing Stone [5]','Somber Smithing Stone [6]'], clue:'A church in the Mountaintops has the next permanent somber-stone supply unlock.', when:f=>Boolean(f.mountaintopsGrace) },
  { id:'somber-4', family:'somber', name:"Somberstone Miner's Bell Bearing [4]", region:'mountaintops', regionName:'Crumbling Farum Azula', location:'Tempest-Facing Balcony', source:'Found on a corpse on the route forward.', unlocks:['Somber Smithing Stone [7]','Somber Smithing Stone [8]','Sanctuary Stone'], clue:'Late story progression puts another somber-stone supply unlock directly on the path.', when:f=>Boolean(f.erdtreeFire||f.greatBridgeGrace) },
  { id:'somber-5', family:'somber', name:"Somberstone Miner's Bell Bearing [5]", region:'mountaintops', regionName:'Crumbling Farum Azula', location:'Beside the Great Bridge approach', source:'Found on a corpse in the late Farum Azula route.', unlocks:['Somber Smithing Stone [9]'], clue:'The final renewable somber-stone tier is hidden late in the crumbling city.', when:f=>Boolean(f.greatBridgeGrace) },
];

export const reachableForgeSupply = flags => FORGE_SUPPLY.filter(item=>item.when(flags));
