const unlocked = predicate => predicate;

export const STORY_BEATS = [
  { id:'opening', chapter:'The Lands Between', title:'The Shattering and the return of the Tarnished', when:()=>true, summary:'The Elden Ring was shattered, the demigods claimed Great Runes, and the resulting war produced no lord. Grace calls exiled Tarnished back to the Lands Between to seek the Elden Ring.', glossary:['elden-ring','marika','grace','tarnished','shattering'], learnMore:'The opening gives you the political result, not the whole cause. The game gradually reveals how the Golden Order broke down and why the Tarnished were called back.' },
  { id:'melina', chapter:'The Lands Between', title:'A maiden offers an accord', when:f=>f.torrent, summary:'Melina offers to act as your maiden, giving you the ability to turn runes into strength. She asks to be taken toward the Erdtree and entrusts Torrent to you.', glossary:['melina','torrent','erdtree'], learnMore:'Her stated purpose is tied to a task given by her mother inside the Erdtree. The exact nature of that task unfolds much later.' },
  { id:'roundtable', chapter:'The Lands Between', title:'Roundtable Hold', when:f=>f.roundtable, summary:'You are brought to a gathering place for Tarnished pursuing Great Runes and the title of Elden Lord. Many NPC stories intersect here.', glossary:['roundtable','two-fingers','gideon','fia','hewg'], learnMore:'The Hold behaves like a place outside the ordinary geography of the Lands Between. Its condition mirrors larger changes in the world.' },
  { id:'stormveil', chapter:'Great Runes', title:'Stormveil and the Golden Lineage', when:f=>f.margit||f.godrick, summary:'Stormveil introduces the decayed descendants of the Golden Lineage and shows what obsession with Great Runes has done to the demigods and their followers.', glossary:['godrick','godfrey','golden-lineage','grafting'], learnMore:'Godrick’s obsession with grafting reflects his insecurity about diluted divine blood rather than simple strength.' },
  { id:'liurnia', chapter:'Great Runes', title:'Liurnia and the House of the Moon', when:f=>f.liurniaGrace||f.godrick, summary:'Liurnia reveals a second great power: Raya Lucaria and the Carian royal family, whose history is entangled with Radagon and the Golden Order.', glossary:['rennala','radagon','carian','ranni'], learnMore:'The academy and Carian royals are not the same institution. Their alliance and later fracture explain much of Liurnia’s civil conflict.' },
  { id:'rennala', chapter:'Great Runes', title:'Rennala and rebirth', when:f=>f.rennala, summary:'Rennala remains in the Grand Library with the amber egg Radagon left her. Defeating her does not kill her; she becomes the source of character rebirth.', glossary:['rennala','radagon','great-runes'], learnMore:'The Great Rune of the Unborn is tied to the egg rather than to Rennala in the same way the shardbearers carry theirs.' },
  { id:'ranni-start', chapter:'Hidden paths', title:'Ranni’s service', when:f=>f.ranniRiseGrace||f.ranniStory, summary:'Ranni asks you to enter her service and pursue a hidden path connected to Nokron, the Fingers, and her rejection of the role chosen for her.', glossary:['ranni','blaidd','iji','seluvis','two-fingers'], learnMore:'This thread exposes some of the clearest evidence that the current cosmic order is contested rather than universally accepted.' },
  { id:'radahn', chapter:'Hidden paths', title:'The stars move again', when:f=>f.radahn, summary:'Starscourge Radahn’s defeat releases the stars he had arrested. A falling star opens a route into Nokron and advances several NPC stories.', glossary:['radahn','nokron','ranni','alexander'], learnMore:'Radahn holding the stars has practical consequences for fate in a world where the motion of stars is tied to Carian destinies.' },
  { id:'nokron', chapter:'Hidden paths', title:'Nokron and the Fingerslayer Blade', when:f=>f.nightsSacredGroundGrace||f.ainselMainGrace, summary:'Nokron contains the treasure Ranni seeks: a weapon created to harm the Fingers. Handing it over commits her story to its next phase and ends Seluvis’s opportunity to act.', glossary:['nokron','ranni','two-fingers','seluvis'], learnMore:'The Eternal Cities carry a long history of opposition to the Greater Will and its envoys.' },
  { id:'altus', chapter:'The Erdtree', title:'Approaching the capital', when:f=>f.altusGrace, summary:'Altus Plateau puts the Erdtree and Leyndell at the center of your journey. Several NPC stories advance simply because you have reached this stage of the world.', glossary:['altus','leyndell','erdtree'], learnMore:'Reaching Altus can also trigger the Radahn Festival if it has not already begun, which is why the companion warns before this threshold.' },
  { id:'volcano', chapter:'Competing orders', title:'Volcano Manor and recusancy', when:f=>f.volcanoManorGrace||f.rykard, summary:'Volcano Manor recruits Tarnished willing to hunt their own kind and reject the Erdtree. Its lord’s rebellion is ideological as well as monstrous.', glossary:['rykard','tanith','volcano-manor','recusant'], learnMore:'The Manor’s contracts, Rya, Bernahl, and Patches all intersect. Defeating Rykard early can cut off parts of those stories.' },
  { id:'leyndell', chapter:'The Erdtree', title:'Leyndell and the sealed Erdtree', when:f=>f.eastCapitalGrace||f.morgott, summary:'At the capital you discover that simply gathering Great Runes is not enough. Access to the Erdtree itself is barred, forcing the journey toward the Mountaintops.', glossary:['morgott','leyndell','erdtree','omens'], learnMore:'Morgott’s devotion to the order that rejected him is one of the game’s central character contradictions.' },
  { id:'forge', chapter:'The Erdtree', title:'The Forge of the Giants', when:f=>f.footForgeGrace||f.fireGiant, summary:'The path reaches the means to burn the impenetrable thorns. The boss is not the actual world-state cutoff; the decision at the Forge afterward is.', glossary:['fire-giants','melina','forge','erdtree'], learnMore:'The companion deliberately warns after Fire Giant but before the Forge interaction because that is the important state transition.' },
  { id:'farum', chapter:'Destined Death', title:'Crumbling Farum Azula', when:f=>f.erdtreeFire||f.greatBridgeGrace, summary:'After the Forge, you reach a place outside ordinary time where the Rune of Death is guarded. Releasing it is required for the final transformation of the capital.', glossary:['farum-azula','maliketh','destined-death'], learnMore:'Farum Azula connects dragons, ancient lordship, and the sealing of Destined Death.' },
  { id:'ashen', chapter:'Endgame', title:'The capital after Destined Death', when:f=>f.maliketh, summary:'With Destined Death unbound, Leyndell changes permanently and the final sequence of challenges opens.', glossary:['destined-death','leyndell','marika','radagon'], learnMore:'This is one of the clearest irreversible base-game thresholds, which is why the companion warns at Beside the Great Bridge.' },
  { id:'dlc-entry', chapter:'Realm of Shadow', title:'Following Miquella', when:f=>f.dlcEntry, summary:'At Miquella’s cocoon you enter the Realm of Shadow, where Miquella has abandoned pieces of himself while pursuing a path to godhood.', glossary:['miquella','realm-of-shadow','scadutree','leda'], learnMore:'The DLC reframes Miquella from a distant figure into the center of an active pilgrimage. Early followers speak under the influence of his charm.' },
  { id:'dlc-crosses', chapter:'Realm of Shadow', title:'Miquella’s crosses', when:f=>f.dlcEntry, summary:'Crosses mark places where Miquella divested himself of body, lineage, or other parts of his identity. His followers use them as a trail.', glossary:['miquella','crosses','leda','hornsent'], learnMore:'The crosses are both literal route markers and evidence of what Miquella believes must be discarded to reach divinity.' },
  { id:'dlc-charm', chapter:'Realm of Shadow', title:'A Great Rune breaks and a charm ends', when:f=>f.dlcScaduAltus||f.dlcShadowKeep, summary:'Approaching Shadow Keep breaks Miquella’s Great Rune and the charm over his followers. Their suppressed doubts and agendas surface immediately.', glossary:['miquella','great-runes','leda','ansbach','freyja','hornsent','thiollier','moore'], learnMore:'This is the DLC’s first major NPC synchronization point. The companion recommends talking to every follower before and after it triggers.' },
  { id:'messmer', chapter:'Realm of Shadow', title:'Messmer and the crusade', when:f=>f.dlcShadowKeep||f.messmerDefeated, summary:'Shadow Keep reveals the force behind the purge of the Hornsent: Messmer, a son of Marika left in the Realm of Shadow with a crusading army.', glossary:['messmer','marika','hornsent','shadow-keep'], learnMore:'The DLC uses Messmer’s campaign to expose a buried part of Marika’s history that the Lands Between largely erased.' },
  { id:'st-trina', chapter:'Realm of Shadow', title:'St. Trina', when:f=>f.dlcCerulean||f.putrescentDefeated, summary:'Deep below the Cerulean Coast, Thiollier’s search leads to St. Trina and a revelation about Miquella’s discarded self.', glossary:['st-trina','miquella','thiollier'], learnMore:'This thread is intentionally shown with layered spoilers because its meaning changes how you read Miquella’s goal.' },
  { id:'metyr', chapter:'Fingers', title:'The Mother of Fingers', when:f=>f.metyrDefeated, summary:'Ymir’s quest reaches Metyr, Mother of Fingers, adding crucial context to the Two Fingers and the reliability of divine guidance.', glossary:['metyr','ymir','two-fingers','greater-will'], learnMore:'This is one of the DLC’s biggest cosmology revelations. The companion keeps the interpretation behind Learn More until you reach it.' },
  { id:'bayle', chapter:'Dragons', title:'Bayle and the ancient dragons', when:f=>f.dlcJaggedPeak||f.bayleDefeated, summary:'Igon and the Dragon Communion Priestess lead into a feud reaching back to the ancient dragons and Bayle’s rebellion against Placidusax.', glossary:['bayle','igon','placidusax','dragon-communion'], learnMore:'The visual damage on Bayle and Placidusax is part of the environmental evidence tying their conflict together.' },
  { id:'sealing-tree', chapter:'Realm of Shadow', title:'The Sealing Tree', when:f=>f.rominaDefeated||f.dlcEnirIlim, summary:'After Romina, burning the Sealing Tree opens Enir-Ilim. This is the DLC’s major point of no return for most follower questlines.', glossary:['romina','enir-ilim','miquella','leda'], learnMore:'The companion treats this as a hard cleanup checkpoint and surfaces every unresolved follower before you burn it.' },
  { id:'enir', chapter:'Realm of Shadow', title:'Enir-Ilim and the Gate of Divinity', when:f=>f.dlcEnirIlim, summary:'The pilgrimage reaches the tower and the Gate of Divinity. The surviving followers’ choices converge before the final confrontation.', glossary:['enir-ilim','miquella','gate-of-divinity','leda'], learnMore:'The NPC battle here reflects which followers you helped, opposed, or left unresolved.' },
  { id:'dlc-end', chapter:'Realm of Shadow', title:'Miquella’s promised order', when:f=>f.consortDefeated, summary:'The final memory clarifies Miquella’s childhood vow and the identity of the promised consort. It also leaves open questions about consent, compulsion, and what Miquella’s age would have meant in practice.', glossary:['miquella','radahn','malenia','mohg'], learnMore:'Some parts are explicit in dialogue and remembrance text; other connections remain interpretive. The glossary separates confirmed facts from community theory.' },
];

export const GLOSSARY = [
  ['elden-ring','Elden Ring','A metaphysical ordering principle expressed through Great Runes. It is not merely a piece of jewelry.'],
  ['marika','Queen Marika','The vessel of the Elden Ring and god of the Golden Order. The DLC reveals a hidden history in the Realm of Shadow.'],
  ['radagon','Radagon','Champion, second Elden Lord, and a figure whose identity is inseparable from Marika.'],
  ['grace','Grace','Golden guidance associated with the Erdtree. It calls the Tarnished back and points toward major objectives.'],
  ['tarnished','Tarnished','Warriors and descendants once stripped of grace and banished, later called back to seek lordship.'],
  ['shattering','The Shattering','Both the breaking of the Elden Ring and the war among demigods that followed.'],
  ['erdtree','Erdtree','The great golden tree at the center of the Golden Order and the present age.'],
  ['two-fingers','Two Fingers','Envoys who interpret a higher will for the Roundtable and other divine towers. Later discoveries complicate their authority.'],
  ['greater-will','Greater Will','A distant cosmic power associated with the Fingers and the Elden Beast; the exact nature and immediacy of its influence is debated.'],
  ['roundtable','Roundtable Hold','A hub for Tarnished pursuing Great Runes and Elden Lordship.'],
  ['gideon','Sir Gideon Ofnir','The All-Knowing, leader-like figure at Roundtable Hold who gathers information on shardbearers.'],
  ['fia','Fia','A Deathbed Companion whose story opens a competing vision of death within Order.'],
  ['hewg','Smithing Master Hewg','Roundtable smith bound to a task involving a weapon capable of slaying a god.'],
  ['godfrey','Godfrey','First Elden Lord and leader of the Tarnished before their exile.'],
  ['golden-lineage','Golden Lineage','Descendants of Godfrey and Marika, including Godwyn and the distant line that reaches Godrick.'],
  ['grafting','Grafting','Godrick’s practice of attaching the limbs and bodies of others to himself to manufacture strength.'],
  ['rennala','Rennala','Queen of the Full Moon, Carian royal and former head of Raya Lucaria.'],
  ['carian','Carian Royal Family','Moon-aligned royal house whose sorcery and fate are closely tied to the stars.'],
  ['ranni','Ranni the Witch','Empyrean who rejects the role chosen for her by the Fingers and pursues a radically different order.'],
  ['blaidd','Blaidd','Ranni’s shadow, created to serve an Empyrean but caught between loyalty and the purpose imposed on him.'],
  ['iji','War Counselor Iji','Carian giant smith and adviser to Ranni.'],
  ['seluvis','Preceptor Seluvis','A servant of Ranni with his own deeply coercive agenda.'],
  ['great-runes','Great Runes','Major shards of the Elden Ring claimed by demigods after the Shattering.'],
  ['radahn','Starscourge Radahn','Demigod general who learned gravity magic and halted the stars, affecting Carian fate.'],
  ['nokron','Nokron','One of the Eternal Cities, associated with a civilization that opposed the Greater Will.'],
  ['altus','Altus Plateau','Golden highland leading toward Leyndell.'],
  ['leyndell','Leyndell','Royal capital at the base of the Erdtree.'],
  ['rykard','Rykard','Praetor and lord of Volcano Manor who embraced blasphemy against the Erdtree.'],
  ['tanith','Tanith','Lady of Volcano Manor and Rykard’s consort.'],
  ['volcano-manor','Volcano Manor','Home of recusants who reject the Erdtree and hunt other Tarnished.'],
  ['recusant','Recusants','Tarnished who oppose the Two Fingers and hunt their own.'],
  ['morgott','Morgott','Omen king who fiercely protects the Erdtree despite the order’s rejection of his kind.'],
  ['omens','Omens','People born with horns and other Crucible traits, persecuted under the Golden Order.'],
  ['fire-giants','Fire Giants','Ancient enemies of the Erdtree whose flame can burn what ordinary fire cannot.'],
  ['melina','Melina','Your traveling maiden, linked to the Erdtree and to a purpose given by her mother.'],
  ['forge','Forge of the Giants','The source of ruinous flame required to burn the Erdtree’s thorns.'],
  ['farum-azula','Crumbling Farum Azula','Ancient floating ruins associated with dragons, beastmen and a former age of lordship.'],
  ['maliketh','Maliketh','Marika’s shadow and keeper of Destined Death.'],
  ['destined-death','Destined Death','The Rune of Death, removed from the Golden Order and sealed away.'],
  ['miquella','Miquella','Empyrean child of Marika and Radagon. The DLC follows his path through the Realm of Shadow toward godhood.'],
  ['realm-of-shadow','Realm of Shadow','A land hidden from the Lands Between, containing the site of Marika’s origins and Messmer’s crusade.'],
  ['scadutree','Scadutree','Shadowed counterpart to the Erdtree dominating the Realm of Shadow.'],
  ['leda','Needle Knight Leda','Follower of Miquella whose loyalty becomes increasingly dangerous after the charm breaks.'],
  ['crosses','Miquella’s Crosses','Markers recording pieces of himself Miquella abandoned on his path.'],
  ['hornsent','Hornsent','People of the Realm of Shadow centered on tower culture and Crucible traits, later targeted by Messmer’s purge.'],
  ['ansbach','Sir Ansbach','Former Pureblood Knight of Mohg who follows Miquella to understand what happened to his lord.'],
  ['freyja','Redmane Freyja','Former Redmane soldier seeking answers about Radahn and Miquella.'],
  ['thiollier','Thiollier','Follower of Miquella devoted to poison and St. Trina.'],
  ['moore','Moore','Forager Brood merchant among Miquella’s followers.'],
  ['messmer','Messmer the Impaler','Son of Marika and commander of the crusade against the Hornsent.'],
  ['shadow-keep','Shadow Keep','Messmer’s fortress and a major DLC quest convergence point.'],
  ['st-trina','St. Trina','Mysterious figure associated with sleep and, in the DLC, directly tied to Miquella.'],
  ['metyr','Metyr, Mother of Fingers','Ancient mother of the Fingercreepers and Two Fingers, central to Ymir’s cosmological revelations.'],
  ['ymir','Count Ymir','High priest of the Cathedral of Manus Metyr who seeks to reinterpret the Fingers’ origin.'],
  ['bayle','Bayle the Dread','Ancient drake and enemy of Dragonlord Placidusax.'],
  ['igon','Igon','Wounded drake warrior whose entire remaining purpose is to face Bayle.'],
  ['placidusax','Dragonlord Placidusax','Ancient dragon lord of a previous age, maimed in conflict with Bayle.'],
  ['dragon-communion','Dragon Communion','Practice of consuming dragon hearts to inherit draconic power, with physical and spiritual consequences.'],
  ['romina','Romina, Saint of the Bud','Guardian of the Church of the Bud and bearer of scarlet rot imagery in Rauh.'],
  ['enir-ilim','Enir-Ilim','Tower settlement hidden by the Sealing Tree and home to the Gate of Divinity.'],
  ['gate-of-divinity','Gate of Divinity','Ritual site associated with ascent to godhood.'],
  ['malenia','Malenia','Empyrean twin of Miquella, afflicted by Scarlet Rot and fiercely devoted to her brother.'],
  ['mohg','Mohg','Lord of Blood who carried Miquella’s cocoon; the DLC complicates how much agency he had in that relationship.'],
  ['torrent','Torrent','Spectral steed who chooses the Tarnished and was known to Melina before your meeting.'],
].map(([id,name,summary])=>({id,name,summary}));

export const THEORY_CARDS = [
  { id:'marika-motive', title:'Why did Marika shatter the Elden Ring?', unlock:f=>f.maliketh||f.dlcShadowKeep, confirmed:'The game confirms Marika shattered the Elden Ring and Radagon tried to repair it.', theory:'Her motive is deliberately layered. Grief, rebellion against the existing order, long-term planning, and dissatisfaction with the Greater Will are all argued from different evidence.', caution:'Interpretation, not a single confirmed answer.' },
  { id:'miquella-charm', title:'How much of Miquella’s following is voluntary?', unlock:f=>f.dlcScaduAltus, confirmed:'The DLC explicitly shows that Miquella’s charm influenced his followers and breaks when his Great Rune shatters.', theory:'Their behavior afterward suggests affection, debt, ideology and compulsion were mixed differently for each person.', caution:'The game leaves individual degrees of consent open to interpretation.' },
  { id:'mohg-agency', title:'What changes about how we read Mohg?', unlock:f=>f.dlcScaduAltus||f.mohg, confirmed:'The DLC reveals that Miquella could charm others and that Mohg’s body becomes important to Miquella’s plan.', theory:'This reframes, but does not erase, everything shown in Mohgwyn Palace. How much responsibility to assign Mohg before and during the charm remains debated.', caution:'Keep base-game evidence and DLC revelations separate before drawing conclusions.' },
  { id:'fingers-silence', title:'Are the Fingers really receiving current instructions?', unlock:f=>f.metyrDefeated, confirmed:'Ymir and Metyr’s quest strongly undermines the assumption that Finger guidance is a simple live line to the Greater Will.', theory:'Many players read the Golden Order as operating on inherited or broken instructions rather than continuous divine communication.', caution:'The exact chronology and nature of the Greater Will’s silence is still interpreted.' },
];

export const STORY_VIDEOS = [
  { id:'official-story-trailer', kind:'official', title:'ELDEN RING — Story Trailer', creator:'Bandai Namco Entertainment', url:'https://www.youtube.com/watch?v=K_03kFqWfqs', unlock:()=>true, spoiler:'Official pre-release story material. Safe as an opening-world premise, but deliberately richer than the opening cinematic.' },
  { id:'official-summary', kind:'official', title:'ELDEN RING Story Summary Explained', creator:'Bandai Namco', url:'https://en.bandainamcoent.eu/elden-ring/news/elden-ring-story-summary-explained', unlock:f=>f.limgrave, spoiler:'Official broad premise/early-journey recap; no late ending explanation.' },
  { id:'dlc-story-trailer', kind:'official', title:'Shadow of the Erdtree — Story Trailer', creator:'Bandai Namco Entertainment America', url:'https://www.youtube.com/watch?v=J9Bm5U-MJZw', unlock:f=>f.dlcEntry, spoiler:'Official pre-release story trailer. Shows the Realm of Shadow premise and Messmer imagery but not the DLC ending.' },
  { id:'base-lore', kind:'deep-dive', title:"Elden Ring's Lore — Explained", creator:'VaatiVidya', url:'https://www.youtube.com/watch?v=DYDs_Inzkz4', unlock:f=>f.eldenBeast, spoiler:'Broad base-game spoilers. Hidden until the base-game final boss is defeated.' },
  { id:'dlc-revelations', kind:'deep-dive', title:'Lore Revelations in the Shadow of the Erdtree', creator:'VaatiVidya', url:'https://www.youtube.com/watch?v=ldTQoUxROzY', unlock:f=>f.consortDefeated, spoiler:'Full DLC spoilers. Hidden until the DLC final boss is defeated.' },
  { id:'dlc-cutscenes', kind:'community-cutscenes', title:'Shadow of the Erdtree full story / cutscenes', creator:"Gamer's Little Playground", url:'https://www.youtube.com/watch?v=sQ9v59LiOnE', unlock:f=>f.consortDefeated, spoiler:'Full DLC playthrough and cutscenes; hidden until completion.' },
];

export function unlockedStory(flags) { return STORY_BEATS.filter(beat => unlocked(beat.when)(flags)); }
export function glossaryById(id) { return GLOSSARY.find(entry=>entry.id===id); }
